//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZavod.Data.orderDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderParams
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<int> Price { get; set; }
        public string DoorType { get; set; }
        public Nullable<int> Pos { get; set; }
        public string ParamName { get; set; }
    }
}
